<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Flujo Completo 20 pies</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>210abbdd-10f5-41bd-9337-5ec3ffe7f962</testSuiteGuid>
   <testCaseLink>
      <guid>1dc22bb9-4b30-481c-83ff-4382239d9fdb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Generar_Excel_Pedidos_20pies</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>89616a7b-3011-48de-a011-c8d9a5c6ea9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Crear_Pedido_20pies</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8bcc48f-0618-41bd-9bee-a822d48765c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9c2c642-1275-4e1e-919f-00d2394ccd39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3cd746d-3c78-4aa3-b6e5-6150a5f9d8f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c3c0d12-0c27-4610-97e7-a0987e67a81b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bfa554c-b7d3-4f3b-b61d-73ca11f6644f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e647ebb6-2581-4630-8f62-e6b9723fb007</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c26997d4-d1e9-4871-92b6-ef74f38398db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2abbde82-a952-4b29-bd72-efe4479226ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7eea642-0c56-4f30-83ae-9fb4d6a96437</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e533dc2a-8ccb-4cda-b9a4-924ac1185a82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12cd232d-116f-44ec-ad68-87d5ee1625c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dba97a4a-252e-4839-854f-6618f2932cac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>467987af-c19e-4d35-9c55-9b779415ccc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f336fc83-e793-495d-b73e-cb1f990efa7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d15c4d3-f641-4e07-9964-b7c3fcdf5271</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48bc8f00-5ea5-4382-914b-4f7d258a8a38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7a76be4-f0cd-42f5-9bce-779989919a58</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Generar_Excel_Aprobaciones</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d9d65dc7-5fb2-40d1-a187-1ffc98bd90b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Aprobar_Ventas</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34765a09-cc66-4ed0-810c-42f7a0718bfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01a1edf3-1336-4dfb-90ed-cd37ddefa05b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68a6d548-09a6-4606-8aa8-b4e52abb19b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1cf1487-f5c3-447d-afae-5e859e55442c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7964eb79-f18c-4114-9c7b-52c2fa600f77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4296e2c4-04aa-4772-9687-590f38a237de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10e3e30e-b873-4671-abe4-c412fce24de8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Aprobar_Financiera</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>843159fb-33ff-47b6-a934-23109ea3ecc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8611b1f-1baf-4587-85eb-d4c34b2f05c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>340cbecb-3d61-47a7-b6d3-e391aacd2132</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48c2e3f3-4f82-47c7-90cd-25e2cf3f626e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5368b3b-a230-40d0-a80b-d1c41c96ac91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94b82c47-b740-47e6-85ac-a9d80531462b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d49dd983-4f72-478d-b5a3-1da5d0143b4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Aprobar_Produccion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8daa739a-8a1d-4a8f-9d6e-ba9794febcc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bdf01d6-fd8e-441b-adf2-fbad8fdf8d5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64a292b6-9261-4fe4-8225-614270cd369c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10df624b-bdbc-487c-8687-125c6bb1319a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e21ebd6-aa79-4ce8-9286-e24e5e31f1eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efd9f664-ef97-4b1d-9edb-11f8778f81aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfbb4a45-9c74-4b60-9983-4e251facfdaf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>694d79f7-c166-47f3-8583-ef9e18fac00f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Generar_Excel_CargosLogisticos</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2d82b3af-a379-49d2-b7a4-ddeb335794c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Agregar_Cargos_Logisticos</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e3562be-88cc-4030-aa76-40bd6889a1b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1232ff6-adac-417c-be89-e06530cf5ddd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76f6417f-47bf-492f-bb15-6d77326a5356</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f951296-9d30-4eca-bcaa-d8e03e7d3bae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e5c43c0-a274-474f-a3fb-881bb9c8064a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1861e52-1f65-46ad-a520-85fb5861eb6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ede25ea-4b59-46b3-80dc-92c2545a1938</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>981fa9bf-7451-418a-aabe-ed121d435b8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Generar_Excel_Produccion</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0c999476-ed65-4118-86dd-468208d2a158</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Orden_Produccion</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e2df030-a28e-47c8-888c-bbd77bd1ec4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca5cb557-f7f1-453a-8994-832b591dc7af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>577a38d6-c645-42c7-8360-a114a529328d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3baf5a54-ce27-4a10-9783-7e2a9b8e084a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d32776fe-1f3d-4b19-a2d6-a598b6d3a760</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Generar_Excel_Inventario</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f605a06e-d45b-438d-82e9-24b654a62523</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Agregar_Inventario</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cda5e9b-e85c-4b36-991a-34eaf136ad27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e71506c8-b054-4fec-8189-f794f07aabfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>474cdeda-903e-4c7b-b32f-c0df8231c026</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50e8741c-bf1e-4575-97f5-6d13dba620e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04719b06-1d2c-4e93-a2f1-b844706ba2f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44eee2c5-4285-4813-ac3f-1432b41e3133</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Generar_Excel_Despachar</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c4c432da-4aae-4859-806f-b24ac03353ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Despachar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bacfa159-4344-4ff5-bc05-024b60d0d77f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fc82bd5-9929-4689-97ca-d13c78270e98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f696116-87df-4092-92d7-2d8953ef2da4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97c770da-9151-4f2c-b7be-8c8ab8a9d3d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e52f68db-dace-4d04-9d2b-8ee81be90845</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>359f4750-764a-40e4-a27f-07d943ef5190</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Remover_pedidos</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
