<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>2-Aprobaciones_20_TestSuites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>05ba3757-aebb-4398-a8fe-fdaa8889b54e</testSuiteGuid>
   <testCaseLink>
      <guid>3de94f53-2291-4470-a251-de7ccc49666d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Generar_Aprobaciones_20pies</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c5990de3-85c8-45b6-afab-2ce17959307d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Aprobar_Ventas_20pies</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01a1edf3-1336-4dfb-90ed-cd37ddefa05b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68a6d548-09a6-4606-8aa8-b4e52abb19b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1cf1487-f5c3-447d-afae-5e859e55442c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7964eb79-f18c-4114-9c7b-52c2fa600f77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4296e2c4-04aa-4772-9687-590f38a237de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34765a09-cc66-4ed0-810c-42f7a0718bfa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3aca0da-07c1-459b-b0ee-4a89525a1ac0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Aprobar_Financiera_20pies</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8611b1f-1baf-4587-85eb-d4c34b2f05c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>340cbecb-3d61-47a7-b6d3-e391aacd2132</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48c2e3f3-4f82-47c7-90cd-25e2cf3f626e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5368b3b-a230-40d0-a80b-d1c41c96ac91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94b82c47-b740-47e6-85ac-a9d80531462b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>843159fb-33ff-47b6-a934-23109ea3ecc2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00bbe460-a376-4fe4-855d-528cc896fc27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Aprobar_Produccion_20pies</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8daa739a-8a1d-4a8f-9d6e-ba9794febcc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bdf01d6-fd8e-441b-adf2-fbad8fdf8d5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64a292b6-9261-4fe4-8225-614270cd369c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10df624b-bdbc-487c-8687-125c6bb1319a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e21ebd6-aa79-4ce8-9286-e24e5e31f1eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efd9f664-ef97-4b1d-9edb-11f8778f81aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfbb4a45-9c74-4b60-9983-4e251facfdaf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
