<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>3-AgregarLogistica_20_TestSuites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>6a0225de-0408-4693-a134-f12a81a98597</testSuiteGuid>
   <testCaseLink>
      <guid>c3c00368-8635-44be-9ad9-999592b7c16e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Generar_CargosLogisticos_20pies</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8ca0ecf6-af69-41a4-8c47-dc6f83daa9cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Agregar_Cargos_Logisticos_20pies</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1232ff6-adac-417c-be89-e06530cf5ddd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76f6417f-47bf-492f-bb15-6d77326a5356</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f951296-9d30-4eca-bcaa-d8e03e7d3bae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e5c43c0-a274-474f-a3fb-881bb9c8064a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1861e52-1f65-46ad-a520-85fb5861eb6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ede25ea-4b59-46b3-80dc-92c2545a1938</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e3562be-88cc-4030-aa76-40bd6889a1b0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
