<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>4-GenerarProduccion_20pies_TestSuites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4fb61eaa-9467-4e95-ac69-c6350def221e</testSuiteGuid>
   <testCaseLink>
      <guid>32675ce7-d2ad-4e9a-86e5-545b7f8f4431</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Generar_Produccion_20pies</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3cfccd5e-7cdf-4658-a7d4-a33718e168a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Orden_Produccion_20pies</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e2df030-a28e-47c8-888c-bbd77bd1ec4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca5cb557-f7f1-453a-8994-832b591dc7af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>577a38d6-c645-42c7-8360-a114a529328d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cc52665-9a6e-4fe5-a7ef-d0d604354cb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3baf5a54-ce27-4a10-9783-7e2a9b8e084a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3349d306-c1e4-41f7-9ac6-eac86df5cfb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4513d383-446e-4c7c-bd71-04db1d5f2d65</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
