<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>5-Despachar_20pies_TestSuites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>21cc7c29-391f-4ec8-9d93-62159f96d840</testSuiteGuid>
   <testCaseLink>
      <guid>29ce1e78-6553-4aa2-86d3-50317d71a8b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Generar_Despachar_20pies</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>602b4ce2-c0a7-455e-ab10-162ecf302c91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Secuencias de Ejecucion/TC_Despachar_20pies</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d057216-3997-46ac-9cdf-0a03de6369f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fc82bd5-9929-4689-97ca-d13c78270e98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f696116-87df-4092-92d7-2d8953ef2da4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97c770da-9151-4f2c-b7be-8c8ab8a9d3d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e52f68db-dace-4d04-9d2b-8ee81be90845</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
