<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_opcion_compra</name>
   <tag></tag>
   <elementGuidId>a14bd2a1-b67c-458c-9730-de45ebfa25e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;distribucion_contenedor&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'distribucion_contenedor' and (text() = 'SeleccioneOPCION 2: 18 paletas de cajas de 6 x ¼ galOPCION 3: 20 paletas de cajas de 3 x 1 galOPCION 4: 19 paletas de pailas de 5 galOPCION 5: 20 paletas de tambores de 55 gal OPCION 6: 20 paletas de IBC de 275 gal OPCION 7: 10 Paletas de Tambores de 55 Gal + 7 Paletas de Cajas de 12 x ¼ Gal + 3 Paletas de 3 x 1 GalOPCION 8: 10 paletas de tambores de 55 gal + 7 paletas de cajas de 6 x ¼ galOPCION 9: 10 paletas de tambores de 55 gal + 8 paletas de cajas de 3 x 1 galOPCION 10 : 10 paletas de tambores de 55 gal + 6 paletas de pailas de 5 galOPCION 11: 10 paletas de tambores de 55 gal + 10 paletas de IBC de 275 galOPCION 13 : 9 paletas de cajas de 12 x ¼ gal + 9 paletas de cajas de 6 x ¼ galOPCION 14: 9 paletas de cajas de 12 x ¼ gal + 11 paletas de cajas de 3 x 1 galOPCION 15: 9 paletas de pailas de 5 gal + 9 paletas de cajas de 12 x ¼ gal          OPCION 1: 18 paletas de cajas de 12 x ¼ gal' or . = 'SeleccioneOPCION 2: 18 paletas de cajas de 6 x ¼ galOPCION 3: 20 paletas de cajas de 3 x 1 galOPCION 4: 19 paletas de pailas de 5 galOPCION 5: 20 paletas de tambores de 55 gal OPCION 6: 20 paletas de IBC de 275 gal OPCION 7: 10 Paletas de Tambores de 55 Gal + 7 Paletas de Cajas de 12 x ¼ Gal + 3 Paletas de 3 x 1 GalOPCION 8: 10 paletas de tambores de 55 gal + 7 paletas de cajas de 6 x ¼ galOPCION 9: 10 paletas de tambores de 55 gal + 8 paletas de cajas de 3 x 1 galOPCION 10 : 10 paletas de tambores de 55 gal + 6 paletas de pailas de 5 galOPCION 11: 10 paletas de tambores de 55 gal + 10 paletas de IBC de 275 galOPCION 13 : 9 paletas de cajas de 12 x ¼ gal + 9 paletas de cajas de 6 x ¼ galOPCION 14: 9 paletas de cajas de 12 x ¼ gal + 11 paletas de cajas de 3 x 1 galOPCION 15: 9 paletas de pailas de 5 gal + 9 paletas de cajas de 12 x ¼ gal          OPCION 1: 18 paletas de cajas de 12 x ¼ gal')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>distribucion_contenedor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SeleccioneOPCION 2: 18 paletas de cajas de 6 x ¼ galOPCION 3: 20 paletas de cajas de 3 x 1 galOPCION 4: 19 paletas de pailas de 5 galOPCION 5: 20 paletas de tambores de 55 gal OPCION 6: 20 paletas de IBC de 275 gal OPCION 7: 10 Paletas de Tambores de 55 Gal + 7 Paletas de Cajas de 12 x ¼ Gal + 3 Paletas de 3 x 1 GalOPCION 8: 10 paletas de tambores de 55 gal + 7 paletas de cajas de 6 x ¼ galOPCION 9: 10 paletas de tambores de 55 gal + 8 paletas de cajas de 3 x 1 galOPCION 10 : 10 paletas de tambores de 55 gal + 6 paletas de pailas de 5 galOPCION 11: 10 paletas de tambores de 55 gal + 10 paletas de IBC de 275 galOPCION 13 : 9 paletas de cajas de 12 x ¼ gal + 9 paletas de cajas de 6 x ¼ galOPCION 14: 9 paletas de cajas de 12 x ¼ gal + 11 paletas de cajas de 3 x 1 galOPCION 15: 9 paletas de pailas de 5 gal + 9 paletas de cajas de 12 x ¼ gal          OPCION 1: 18 paletas de cajas de 12 x ¼ gal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;distribucion_contenedor&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='distribucion_contenedor']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datos_principales']/div[2]/div/div/div[2]/div[3]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione una opción de compra'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contenedor de 20 pies'])[4]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contenedor de 20 pies'])[5]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione una presentación'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
