<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sp_Element_presentacion</name>
   <tag></tag>
   <elementGuidId>839a2a75-2d9b-43b8-bf4c-3934f29b3166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>xpath1574179681945</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;datos_principales&quot;]/div[2]/div[1]/div/div[2]/div[4]/div[1]/div[5]
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1574179681945</value>
   </webElementProperties>
</WebElementEntity>
